c:\Users\Timothy\Desktop\BSI\BSI_pjatk2021_TW\BSI_lab3\BSI_lab3\bsi_exercises.h|42|style|catchExceptionByValue|The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++.
c:\Users\Timothy\Desktop\BSI\BSI_pjatk2021_TW\BSI_lab3\BSI_lab3\bsi_exercises.h|46|style|catchExceptionByValue|The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++.
c:\Users\Timothy\Desktop\BSI\BSI_pjatk2021_TW\BSI_lab3\BSI_lab3\bsi_exercises.h|63|style|catchExceptionByValue|The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++.
c:\Users\Timothy\Desktop\BSI\BSI_pjatk2021_TW\BSI_lab3\BSI_lab3\bsi_exercises.h|67|style|catchExceptionByValue|The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++.
c:\Users\Timothy\Desktop\BSI\BSI_pjatk2021_TW\BSI_lab3\BSI_lab3\bsi_exercises.h|101|style|catchExceptionByValue|The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++.
c:\Users\Timothy\Desktop\BSI\BSI_pjatk2021_TW\BSI_lab3\BSI_lab3\bsi_exercises.h|105|style|catchExceptionByValue|The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++.
c:\Users\Timothy\Desktop\BSI\BSI_pjatk2021_TW\BSI_lab3\BSI_lab3\bsi_exercises.h|136|style|catchExceptionByValue|The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++.
c:\Users\Timothy\Desktop\BSI\BSI_pjatk2021_TW\BSI_lab3\BSI_lab3\bsi_exercises.h|140|style|catchExceptionByValue|The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++.
c:\Users\Timothy\Desktop\BSI\BSI_pjatk2021_TW\BSI_lab3\BSI_lab3\bsi_exercises.h|179|style|catchExceptionByValue|The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++.
c:\Users\Timothy\Desktop\BSI\BSI_pjatk2021_TW\BSI_lab3\BSI_lab3\bsi_exercises.h|217|style|catchExceptionByValue|The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++.
c:\Users\Timothy\Desktop\BSI\BSI_pjatk2021_TW\BSI_lab3\BSI_lab3\bsi_exercises.h|234|style|catchExceptionByValue|The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++.
c:\Users\Timothy\Desktop\BSI\BSI_pjatk2021_TW\BSI_lab3\BSI_lab3\bsi_exercises.h|251|style|catchExceptionByValue|The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++.
c:\Users\Timothy\Desktop\BSI\BSI_pjatk2021_TW\BSI_lab3\BSI_lab3\bsi_exercises.h|288|style|catchExceptionByValue|The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++.
c:\Users\Timothy\Desktop\BSI\BSI_pjatk2021_TW\BSI_lab3\BSI_lab3\bsi_exercises.h|305|style|catchExceptionByValue|The exception is caught by value. It could be caught as a (const) reference which is usually recommended in C++.
c:\Users\Timothy\Desktop\BSI\BSI_pjatk2021_TW\BSI_lab3\BSI_lab3\bsi_exercises.h|28|style|shadowFunction|Local variable 'reliability' shadows outer function
